### ISSUE TITLE
Feature Request: Switch cards when mouse wheel scrolled or arrow keys are pressed

### ISSUE THREAD

**Issue by trkaplan** [hamzaerbay/react-content-slider#2]
Switch between cards by scrolling mouse wheel (or trackpad) up or down
or pressing arrow keys (up and down).
Space key would be used to switch next card as well.

**Comment by hamzaerbay** [comment]
Haha, it was disturbing me either. But currently, I'm refactoring the code.

**Comment by hamzaerbay** [comment]
Created another [card](https://github.com/hamzaerbay/react-content-slider/projects/1#card-17207567) for mouse wheel control.
