### ISSUE TITLE
Feature Request: Add preload parameter to the configuration

### ISSUE THREAD

**Issue by trkaplan** [hamzaerbay/react-content-slider#4]
Instead of loading all contents on page load, preload only defined number of cards (e.g. n=3).
Add a loading placeholder for the photos haven't loaded yet. (This only happens, if users switch cards too fast or have a slow connection.)

**Comment by hamzaerbay** [comment]
Strongly agree with you. I'll add lazy loading.

**Comment by hamzaerbay** [comment]
Fixed on https://github.com/hamzaerbay/react-content-slider/pull/8
